name: Continuous Integration Workflow

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/alpine-build-tools
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build check
        run: cmake --build build/release -j$(nproc) -t Aether
      - name: Upload build
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: Aether-Release
          path: build/release/libAether.*
  cppcheck:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/alpine-build-tools
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Setup
        uses: ./.github/actions/setup
      - name: Cppcheck
        run: cmake --build build/debug -j$(nproc) -t cppcheck
      - name: Upload Cppcheck Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          path: build/debug/cppcheck_report.xml
  uncrustify:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/alpine-build-tools
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Setup
        uses: ./.github/actions/setup
      - name: Crust check
        run: cmake --build build/debug -j$(nproc) -t uncrustify-check
      - name: Upload Uncrustify Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: uncrustify-report
          path: build/debug/uncrustify_report.txt
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: d3lta12/alpine-build-tools
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Install Sonar Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v6.0.0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build tests
        run: build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build build/debug -j$(nproc)
      - name: Execute tests
        run: ctest --test-dir build/debug --verbose
      - name: Upload unit tests log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-log
          path: build/debug/Testing/Temporary/LastTest.log
      - name: Generate coverage report
        run: cmake --build build -j$(nproc) -t sonarqube-coverage
      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=delta-12_aether
            -Dsonar.organization=delta-12
            -Dsonar.sources=src
            --define sonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
            --define sonar.coverageReportPaths=build/debug/coverage.xml